# -*- coding: utf-8 -*-
"""goldprice2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NELF9cQEw42fAtiDJhBRp9JOaohX1iJv
"""

# Install required libraries

!pip install twilio scikit-learn pandas matplotlib

# Import libraries

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from twilio.rest import Client
from google.colab import files

# Upload dataset


df = pd.read_csv("FINAL_USO.csv")

# Display first rows

print(df.head())

# Feature selection

X = df[['SP_close','DJ_close','USO_Close','GDX_Close']]
y = df['Close']

# Train-test split

X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42
)

# Train model

model = LinearRegression()
model.fit(X_train, y_train)

# Prediction on test data

y_pred = model.predict(X_test)

# Evaluation

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\n--- Model Evaluation ---")
print("Mean Squared Error:", mse)
print("R2 Score:", r2)

# Latest prediction

latest_data = df[['SP_close','DJ_close','USO_Close','GDX_Close']].iloc[-1]
latest_data = latest_data.values.reshape(1, -1)

predicted_price = model.predict(latest_data)[0]
current_price = df['Close'].iloc[-1]

print("\n--- Prediction ---")
print("Current Gold Price:", current_price)
print("Predicted Price:", predicted_price)

# Trend decision

if predicted_price > current_price:
  trend = "📈 Price may increase"
  recommendation = "HOLD or SELL"
else:
  trend = "📉 Price may decrease"
  recommendation = "BUY GOLD NOW"

print("Trend:", trend)
print("Recommendation:", recommendation)

# Visualization: Actual vs Predicted

plt.figure()
plt.plot(y_test.values, label="Actual")
plt.plot(y_pred, label="Predicted")
plt.legend()
plt.title("Actual vs Predicted Gold Price")
plt.show()

# Visualization: Gold Price Trend

plt.figure()
plt.plot(df['Close'])
plt.title("Gold Price Trend Over Time")
plt.show()

# Twilio SMS Alert (Replace with your credentials)

account_sid = "your_real_sid"
auth_token = "your_real_token"

client = Client(account_sid, auth_token)

message = client.messages.create(
body=f"Gold Price Alert 💰\nCurrent: {current_price}\nPredicted: {predicted_price}\nTrend: {trend}\nRecommendation: {recommendation}",
from_="+19348844404",
to="+919699038949"
)

print("\nSMS Sent Successfully ✔️", message.sid)